path1=/home/arsany/Desktop/lab2/6927-lab2/normalway/mdir
path2=/home/arsany/Desktop/lab2/6927-lab2/normalway/bdir
time=4
mbackups=2
running: foldercreation 
	./backupd.sh ${path1} ${path2} ${time} ${mbackups}
foldercreation:	
	mkdir -p ${path2}	
	
